pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - name: kubectl
    image: cnych/kubectl
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-volume
    command:
    - cat
    tty: true
  - name: nginx
    image: zengemily79/nginx_server2
    command:
    - cat
    tty: true
  volumes:
  - name: kube-volume
    hostPath:
      path: /home/jenkins/.kube
      type: DirectoryOrCreate
"""
    }
  }
  stages {
    stage('Run kubectl') {
      steps {
        container('kubectl') {
          sh 'kubectl get pods'
        }
      }
    }
  }
}
