def branch_version = "bookStore-${UUID.randomUUID().toString()}"

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - name: maven
    image: maven:3.6-alpine
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-volume
    - mountPath: /root/lib
      name: lib-volume    
    command:
    - cat
    tty: true
  - name: docker
    image: docker
    volumeMounts:
    - mountPath: /root/lib
      name: lib-volume
    command:
    - cat
    tty: true
  - name: kubectl
    image: cnych/kubectl
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-volume
    command:
    - cat
    tty: true
  volumes:
  - name: m2-volume
    hostPath:
      path: /var/run/m2
      type: DirectoryOrCreate
  - name: lib-volume
    hostPath:
      path: /var/run/lib
      type: DirectoryOrCreate
  - name: kube-volume
    hostPath:
      path: /home/jenkins/.kube
      type: DirectoryOrCreate
"""
    }
  }
  stages {
    stage('Run MVN') {
      steps {
        container('maven') {
          dir('bookStore') {
            sh 'mvn clean package'
            sh "mkdir -p /root/lib/${branch_version}"
            sh "cp Dockerfile /root/lib/${branch_version}/"
            sh "cp -r target /root/lib/${branch_version}/"
          }
        }
      }
    }
    stage('Run Docker') {
      steps {
        container('docker') {
          sh "echo '10.151.80.30 reg.v2k8s.com' >> /etc/hosts"
          sh 'cat /etc/hosts'
          sh 'echo "{" >> /etc/docker/daemon.json'
          sh 'echo "\"insecure-registries\":[\"reg.v2k8s.com\"]" >> /etc/docker/daemon.json'
          sh 'echo "}" >> /etc/docker/daemon.json'
          sh 'systemctl restart docker'
          dir('lib') {
            dir("${branch_version}") {
              sh 'docker --version'
              sh 'docker login reg.v2k8s.com -u tom -p *Nyz931644'
            }
          }
        }
      }
    }
    stage('Run kubectl') {
      steps {
        container('kubectl') {
          sh 'kubectl get pods'
        }
      }
    }
  }
}
