def branch_version = "slave-${UUID.randomUUID().toString()}"

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - name: maven
    image: maven:3.6-alpine
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-volume
    - mountPath: /root/bookStore-jar
      name: bs-volume    
    command:
    - cat
    tty: true
  - name: docker
    image: docker
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-volume
    command:
    - cat
    tty: true
  - name: kubectl
    image: cnych/kubectl
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-volume
    command:
    - cat
    tty: true
  volumes:
  - name: m2-volume
    hostPath:
      path: /var/run/m2
      type: DirectoryOrCreate
  - name: bs-volume
    hostPath:
      path: /var/run/bookStore-jar
      type: DirectoryOrCreate
  - name: kube-volume
    hostPath:
      path: /home/jenkins/.kube
      type: DirectoryOrCreate
"""
    }
  }
  stages {
    stage('Run MVN') {
      steps {
        container('maven') {
          dir('bookStore') {
            sh 'whoami'
            sh 'ls /root/.m2'
            sh 'mvn clean package'
            sh 'echo ${branch_version}'
          }
        }
      }
    }
    stage('Run kubectl') {
      steps {
        container('kubectl') {
          sh 'kubectl get pods'
        }
      }
    }
  }
}
